binary_sensor:

  - name: "Sonne trifft Sued"
    unique_id: sonne_trifft_sued
    delay_on:
      minutes: 5
    delay_off:
      minutes: 5
    state: >
      {{ state_attr('sun.sun', 'azimuth') | float > 135
         and state_attr('sun.sun', 'azimuth') | float < 225
         and state_attr('sun.sun', 'elevation') | float > 5
         and states('sensor.helligkeit_sud') | float(0) > 8000 }}

  - name: "Sonne trifft West"
    unique_id: sonne_trifft_west
    delay_on:
      minutes: 5
    delay_off:
      minutes: 5
    state: >
      {{ state_attr('sun.sun', 'azimuth') | float > 225
         and state_attr('sun.sun', 'azimuth') | float < 315
         and state_attr('sun.sun', 'elevation') | float > 5
         and states('sensor.helligkeit_west') | float(0) > 8000 }}

  - name: "Sonne trifft Nord"
    unique_id: sonne_trifft_nord
    delay_on:
      minutes: 5
    delay_off:
      minutes: 5
    state: >
      {{ (state_attr('sun.sun', 'azimuth') | float > 315
         or state_attr('sun.sun', 'azimuth') | float < 45)
         and state_attr('sun.sun', 'elevation') | float > 5
         and states('sensor.helligkeit_nord') | float(0) > 8000 }}

sensor:

  - name: "Outdoor Temperature Avg"
    unique_id: outdoor_temperature_avg
    unit_of_measurement: "°C"
    state_class: measurement
    device_class: temperature
    state: >
      {% set sensor = states('sensor.outdoor_temperature') | float(0) %}
      {% set forecast = state_attr('weather.forecast_home', 'temperature') | float(sensor) %}
      {{ ((sensor + forecast) / 2) | round(1) }}

  - name: "Taupunkt Aussen"
    unique_id: taupunkt_aussen
    unit_of_measurement: "°C"
    state: >
      {% set T = states('sensor.outdoor_temperature') | float %}
      {% set RH = states('sensor.outdoor_humidity') | float %}
      {% set a = 17.27 %}
      {% set b = 237.7 %}
      {% set alpha = ((a*T)/(b+T)) + (RH/100)|log %}
      {{ ((b*alpha)/(a-alpha)) | round(2) }}

  - name: "Taupunkt Technikraum"
    unique_id: taupunkt_technikraum
    unit_of_measurement: "°C"
    state: >
      {% set T = states('sensor.engineering_temperature') | float %}
      {% set RH = states('sensor.engineering_humidity') | float %}
      {% set a = 17.27 %}
      {% set b = 237.7 %}
      {% set alpha = ((a*T)/(b+T)) + (RH/100)|log %}
      {{ ((b*alpha)/(a-alpha)) | round(2) }}

  - name: "Taupunkt Hobby"
    unique_id: taupunkt_hobby
    unit_of_measurement: "°C"
    state: >
      {% set T = states('sensor.hobby_temperature') | float %}
      {% set RH = states('sensor.hobby_humidity') | float %}
      {% set a = 17.27 %}
      {% set b = 237.7 %}
      {% set alpha = ((a*T)/(b+T)) + (RH/100)|log %}
      {{ ((b*alpha)/(a-alpha)) | round(2) }}

  - name: "Taupunkt Lager"
    unique_id: taupunkt_lager
    unit_of_measurement: "°C"
    state: >
      {% set T = states('sensor.storage_temperature') | float %}
      {% set RH = states('sensor.storage_humidity') | float %}
      {% set a = 17.27 %}
      {% set b = 237.7 %}
      {% set alpha = ((a*T)/(b+T)) + (RH/100)|log %}
      {{ ((b*alpha)/(a-alpha)) | round(2) }}

  - name: "Outdoor Humidity"
    unique_id: outdoor_humidity_met
    unit_of_measurement: "%"
    state_class: measurement
    device_class: humidity
    state: "{{ state_attr('weather.forecast_home', 'humidity') }}"

  - name: "Lüftung Technikraum"
    unique_id: ventilation_technikraum_level
    state: >
      {% set RH = states('sensor.engineering_humidity') | float(0) %}
      {% set delta = (states('sensor.taupunkt_technikraum') | float) - (states('sensor.taupunkt_aussen') | float) %}
      {% if RH < 55 %}
        Luftfeuchtigkeit Okay
      {% elif delta > 2 %}
        Lüften stark
      {% elif delta > 0 %}
        Lüften wenig
      {% else %}
        Nicht lüften
      {% endif %}

  - name: "Lüftung Hobbyraum"
    unique_id: ventilation_hobby_level
    state: >
      {% set RH = states('sensor.hobby_humidity') | float(0) %}
      {% set delta = (states('sensor.taupunkt_hobby') | float) - (states('sensor.taupunkt_aussen') | float) %}
      {% if RH < 55 %}
        Luftfeuchtigkeit Okay
      {% elif delta > 2 %}
        Lüften stark
      {% elif delta > 0 %}
        Lüften wenig
      {% else %}
        Nicht lüften
      {% endif %}

  - name: "Lüftung Lager"
    unique_id: ventilation_lager_level
    state: >
      {% set RH = states('sensor.storage_humidity') | float(0) %}
      {% set delta = (states('sensor.taupunkt_lager') | float) - (states('sensor.taupunkt_aussen') | float) %}
      {% if RH < 55 %}
        Luftfeuchtigkeit Okay
      {% elif delta > 2 %}
        Lüften stark
      {% elif delta > 0 %}
        Lüften wenig
      {% else %}
        Nicht lüften
      {% endif %}

  - name: "Taupunkt Garage"
    unique_id: taupunkt_garage
    unit_of_measurement: "°C"
    state: >
      {% set T = states('sensor.garagentor_garage_temperature') | float %}
      {% set RH = states('sensor.garagentor_garage_humidity') | float %}
      {% set a = 17.27 %}
      {% set b = 237.7 %}
      {% set alpha = ((a*T)/(b+T)) + (RH/100)|log %}
      {{ ((b*alpha)/(a-alpha)) | round(2) }}

  - name: "Lüftung Garage"
    unique_id: ventilation_garage_level
    state: >
      {% set RH = states('sensor.garagentor_garage_humidity') | float(0) %}
      {% set delta = (states('sensor.taupunkt_garage') | float) - (states('sensor.taupunkt_aussen') | float) %}
      {% if RH < 50 %}
        Luftfeuchtigkeit Okay
      {% elif delta > 2 %}
        Lüften stark
      {% elif delta > 0 %}
        Lüften wenig
      {% else %}
        Nicht lüften
      {% endif %}